package tetris.network;

public enum MessageType
{
	INITIALIZE,
	LIST_GAME, ENTER_GAME, LEAVE_GAME,
	BOARD, LINES, ITEM, CURRENT_PIECE, LIST_GAME_RESULT, PLAYER_INFO, INITIALIZE_REQUEST, 
	GAME_COUNTDOWN, GAME_BEGIN, GAME_END, PING, GAME_RANKING, CHAT;
}
